# Generated by Django 5.1.2 on 2024-10-12 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('contour_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('coordinates', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeBoundary',
            fields=[
                ('boundary_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_type', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalGrid',
            fields=[
                ('digital_grid_id', models.AutoField(primary_key=True, serialize=False)),
                ('power_capacity', models.IntegerField()),
                ('coverage_area', models.FloatField()),
                ('coordinates', models.JSONField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='EcoZone',
            fields=[
                ('ecozone_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('area_covered', models.FloatField()),
                ('protection_level', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('infrastructure_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('infrastructure_condition', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureOutput',
            fields=[
                ('infrastructure_output_id', models.AutoField(primary_key=True, serialize=False)),
                ('infrastructure_type', models.CharField(max_length=100)),
                ('proposed_condition', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('capacity', models.FloatField()),
                ('construction_year', models.IntegerField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationOutput',
            fields=[
                ('population_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_population', models.IntegerField()),
                ('density', models.FloatField()),
                ('distribution', models.CharField(max_length=100)),
                ('age_demographics', models.CharField(max_length=100)),
                ('growth_rate', models.FloatField()),
                ('migration_patterns', models.TextField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedAreasOutput',
            fields=[
                ('protected_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('protection_type', models.CharField(max_length=100)),
                ('area_covered', models.FloatField()),
                ('coordinates', models.JSONField()),
                ('protection_level', models.CharField(max_length=100)),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='Socioeconomic',
            fields=[
                ('socioeconomic_id', models.AutoField(primary_key=True, serialize=False)),
                ('density', models.IntegerField()),
                ('distribution', models.CharField(max_length=100)),
                ('age_demographics', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='SocioeconomicOutput',
            fields=[
                ('socioeconomic_id', models.AutoField(primary_key=True, serialize=False)),
                ('income_levels', models.CharField(max_length=100)),
                ('employment_rate', models.FloatField()),
                ('poverty_rate', models.FloatField()),
                ('education_levels', models.TextField()),
                ('healthcare_access', models.CharField(max_length=100)),
                ('median_income', models.FloatField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalEvolution',
            fields=[
                ('temporal_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('coordinates', models.JSONField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalEvolutionOutput',
            fields=[
                ('temporal_output_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('forecasted_event', models.CharField(max_length=255)),
                ('impact_description', models.TextField()),
                ('coordinates', models.JSONField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='Topography',
            fields=[
                ('topography_id', models.AutoField(primary_key=True, serialize=False)),
                ('elevation', models.FloatField()),
                ('terrain', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationOutput',
            fields=[
                ('transport_output_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_type', models.CharField(max_length=100)),
                ('road_length', models.FloatField()),
                ('coordinates', models.JSONField()),
                ('traffic_density', models.CharField(max_length=100)),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityOutput',
            fields=[
                ('utility_output_id', models.AutoField(primary_key=True, serialize=False)),
                ('utility_type', models.CharField(max_length=100)),
                ('coverage_area', models.FloatField()),
                ('capacity', models.FloatField()),
                ('coordinates', models.JSONField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
        migrations.CreateModel(
            name='ZoningOutput',
            fields=[
                ('zoning_output_id', models.AutoField(primary_key=True, serialize=False)),
                ('zoning_type', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('proposed_capacity', models.IntegerField()),
                ('regulations', models.TextField()),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contour')),
            ],
        ),
    ]
